// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaPozbxi5jNk2aJ6A9NEtHKmLwv6lfw4U',
    appId: '1:188162114393:web:c3eaf03ab67a3929e0c248',
    messagingSenderId: '188162114393',
    projectId: 'tester-39010',
    authDomain: 'tester-39010.firebaseapp.com',
    storageBucket: 'tester-39010.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByuaY1e6GfqEkP7wbGNOMlhXAqBm9hmng',
    appId: '1:188162114393:android:77f21238ff33eb18e0c248',
    messagingSenderId: '188162114393',
    projectId: 'tester-39010',
    storageBucket: 'tester-39010.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCvy1odbWZonhZZYLQPeQw9U_789-skqI',
    appId: '1:188162114393:ios:4319dca0dea54aafe0c248',
    messagingSenderId: '188162114393',
    projectId: 'tester-39010',
    storageBucket: 'tester-39010.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCvy1odbWZonhZZYLQPeQw9U_789-skqI',
    appId: '1:188162114393:ios:7d6465a06040fefce0c248',
    messagingSenderId: '188162114393',
    projectId: 'tester-39010',
    storageBucket: 'tester-39010.appspot.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
